FROM alpine:latest AS builder
WORKDIR /tmp

RUN ver=$(wget --no-check-certificate -qO- https://api.github.com/repos/fatedier/frp/releases/latest | grep 'tag_name' | cut -d\" -f4) && \
    frp_ver="frp_$(echo ${ver} | sed -e 's/^[a-zA-Z]//g')" && \
    wget --no-check-certificate "https://github.com/fatedier/frp/releases/download/${ver}/${frp_ver}_linux_amd64.tar.gz" && \
    tar zxf ${frp_ver}_linux_amd64.tar.gz && \
    mv ${frp_ver}_linux_amd64/frps /usr/bin/frps && \
    mv ${frp_ver}_linux_amd64/frps.toml /etc/frps.toml && \
    chmod +x /usr/bin/frps

FROM alpine:latest
LABEL maintainer="jalena@bcsytv.com"
WORKDIR /root/

RUN apk add --no-cache tzdata

COPY --from=builder /usr/bin/frps /usr/bin/frps
COPY --from=builder /etc/frps.toml /etc/frps.toml

ENTRYPOINT ["/usr/bin/frps"]
CMD ["-c", "/etc/frps.toml"]
